# Generated by Django 5.2.4 on 2025-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boardpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('pageName', models.CharField(max_length=200)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateField(auto_now=True)),
            ],
        ),
    ]
