# Generated by Django 5.2.4 on 2025-07-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardpage_pagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageitem',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
