# Generated by Django 5.2.4 on 2025-07-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_pageitem_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpage',
            name='creatTime',
            field=models.DateTimeField(auto_now_add=True, default='20250731'),
            preserve_default=False,
        ),
    ]
