# Generated by Django 5.2.4 on 2025-09-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_imageitem_pdfitem_textmessage_delete_pageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='display_order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pdfitem',
            name='display_order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='display_order',
            field=models.IntegerField(default=-1),
        ),
    ]
