# Generated by Django 5.2.4 on 2025-09-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_imageitem_display_order_pdfitem_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfitem',
            name='pdf_page',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
