# Generated by Django 5.2.4 on 2025-09-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_pdfitem_pdf_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfitem',
            name='pdf_page',
            field=models.IntegerField(default=0),
        ),
    ]
