# Generated by Django 5.2.4 on 2025-09-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_pdfitem_pdf_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageID', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=-1)),
            ],
        ),
    ]
