# Generated by Django 5.2.4 on 2025-09-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_videoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpage',
            name='autoPlayDelay',
            field=models.IntegerField(default=10),
        ),
    ]
